{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "size": 29324,
          "sha512": "e62fd0f3f03dbcf069852f3d7700ab016fb420d56efd5dd033b8119b74fd37597c2ce20e65a58c0cc6944de79f2a32c8f8081a7987f67e72da202e4e68a3de1d",
          "sha256": "ce5d1d9cbeb435362f43d6086b1b75507b6cbc1e653d9308c7d2879a50831e2d",
          "sha1": "5b8675138e7b1d1fccae80e41dcf1e83f6890f72",
          "md5": "743140af231d8eccb79406286d94d58b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "size": 29324,
          "sha512": "e62fd0f3f03dbcf069852f3d7700ab016fb420d56efd5dd033b8119b74fd37597c2ce20e65a58c0cc6944de79f2a32c8f8081a7987f67e72da202e4e68a3de1d",
          "sha256": "ce5d1d9cbeb435362f43d6086b1b75507b6cbc1e653d9308c7d2879a50831e2d",
          "sha1": "5b8675138e7b1d1fccae80e41dcf1e83f6890f72",
          "md5": "743140af231d8eccb79406286d94d58b"
        }
      ]
    }
  ]
}
