{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "size": 46270,
          "sha512": "e1e73ee2bbd2e4e2e97abb354a3d7b306e401434284b4d75a313e7cfc4427fbefe864b26d2c2bcd13534b77d10bf2faa2aad85d5b5500c6f50c4dbe081c55971",
          "sha256": "b30ff7e4414a3dcf8a02063373b9b3772a965070e94a2f364e79d127108cd114",
          "sha1": "bd0dc1a30608a58df450b2cf30f0d5e75078eeef",
          "md5": "df00c374955be025e2ddf7e4194c9186"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "size": 46270,
          "sha512": "e1e73ee2bbd2e4e2e97abb354a3d7b306e401434284b4d75a313e7cfc4427fbefe864b26d2c2bcd13534b77d10bf2faa2aad85d5b5500c6f50c4dbe081c55971",
          "sha256": "b30ff7e4414a3dcf8a02063373b9b3772a965070e94a2f364e79d127108cd114",
          "sha1": "bd0dc1a30608a58df450b2cf30f0d5e75078eeef",
          "md5": "df00c374955be025e2ddf7e4194c9186"
        }
      ]
    }
  ]
}
