{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "size": 42205,
          "sha512": "e4f0e6c1e30947916f3973d0f3a4cca19954aecc28b45e26657b615056941adb6ef12a310c5ea0201d9f9a5a92c423d67d707712438421634bb755ad585a3e3f",
          "sha256": "e8c2abc527283cd2e628b95affb317963793976df369928197ba0be6033dc9d3",
          "sha1": "e9797d9cf9e7ffb312c8f5b62d101619e9543951",
          "md5": "1855cf5e06d80091085b909ccf7f33c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.6-SNAPSHOT-plain.jar",
          "size": 42205,
          "sha512": "e4f0e6c1e30947916f3973d0f3a4cca19954aecc28b45e26657b615056941adb6ef12a310c5ea0201d9f9a5a92c423d67d707712438421634bb755ad585a3e3f",
          "sha256": "e8c2abc527283cd2e628b95affb317963793976df369928197ba0be6033dc9d3",
          "sha1": "e9797d9cf9e7ffb312c8f5b62d101619e9543951",
          "md5": "1855cf5e06d80091085b909ccf7f33c0"
        }
      ]
    }
  ]
}
