{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.3-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.3-SNAPSHOT-plain.jar",
          "size": 32089,
          "sha512": "1f24a4b49e5748ae3eb83fd752214ebe4e228533b2d7e4bdb63d74bfb278ffe1c35762669449433d1aa3029cf0b03d113d56670434873b4db6f3bacfd48e1762",
          "sha256": "93a657f1df6a50aa6bc617fbcc9ca5dc73d4bb83962d1e04dbad5b117214bf2a",
          "sha1": "a88da7cb732482688666275340eda57dacebc1be",
          "md5": "9cc1f74bd0e795f07a83159868dc0f74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.3-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.3-SNAPSHOT-plain.jar",
          "size": 32089,
          "sha512": "1f24a4b49e5748ae3eb83fd752214ebe4e228533b2d7e4bdb63d74bfb278ffe1c35762669449433d1aa3029cf0b03d113d56670434873b4db6f3bacfd48e1762",
          "sha256": "93a657f1df6a50aa6bc617fbcc9ca5dc73d4bb83962d1e04dbad5b117214bf2a",
          "sha1": "a88da7cb732482688666275340eda57dacebc1be",
          "md5": "9cc1f74bd0e795f07a83159868dc0f74"
        }
      ]
    }
  ]
}
