{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.4-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.4-SNAPSHOT-plain.jar",
          "size": 29208,
          "sha512": "52cb3d83ca829ac088ff5b06ac13c448ce1ef7aedd30598e3c12f89f78bfa8cc89e7b1ff65da4d2442b61f6de889be0353ac5f8228c64dfa6ba544c6722dc1ca",
          "sha256": "98766758c286042442f80883e678cf9c6010130d6cf727ffa0b3405502ed167f",
          "sha1": "9450495e48473abf243e748b96eaf59909a896e2",
          "md5": "7ed2fbb15e1156a8ff2b5f0d18beb4ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.4-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.4-SNAPSHOT-plain.jar",
          "size": 29208,
          "sha512": "52cb3d83ca829ac088ff5b06ac13c448ce1ef7aedd30598e3c12f89f78bfa8cc89e7b1ff65da4d2442b61f6de889be0353ac5f8228c64dfa6ba544c6722dc1ca",
          "sha256": "98766758c286042442f80883e678cf9c6010130d6cf727ffa0b3405502ed167f",
          "sha1": "9450495e48473abf243e748b96eaf59909a896e2",
          "md5": "7ed2fbb15e1156a8ff2b5f0d18beb4ca"
        }
      ]
    }
  ]
}
