{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.9-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.9-SNAPSHOT-plain.jar",
          "size": 29221,
          "sha512": "a86acb5b34c2136b2cd09a41ffb38797145c06a9fb1022531ea62cf7ceda54b310aa3ec20c3cd18c41360025a8f664ad73ca19171c33ff87c0d72e0cc9d55842",
          "sha256": "714452e0c69dc2a33e3c59f19bb745fd9642bae36db595973b820d9bc40aa1cd",
          "sha1": "0ce3b73af37750ab28dc386add6db6384ad61fb7",
          "md5": "fc64f55ccbeb538a9f0c81a89ecff24f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.9-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.9-SNAPSHOT-plain.jar",
          "size": 29221,
          "sha512": "a86acb5b34c2136b2cd09a41ffb38797145c06a9fb1022531ea62cf7ceda54b310aa3ec20c3cd18c41360025a8f664ad73ca19171c33ff87c0d72e0cc9d55842",
          "sha256": "714452e0c69dc2a33e3c59f19bb745fd9642bae36db595973b820d9bc40aa1cd",
          "sha1": "0ce3b73af37750ab28dc386add6db6384ad61fb7",
          "md5": "fc64f55ccbeb538a9f0c81a89ecff24f"
        }
      ]
    }
  ]
}
