{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.2-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.2-SNAPSHOT-plain.jar",
          "size": 12523,
          "sha512": "203d9ceafa2f8087286904cf0b19cdee52886d6f285825ed3f2737a90fbff8839ff02cce3f80b66a0ee0f008b4a0f04c8453826f52ece9daef04d5f8495834e9",
          "sha256": "c51738b93639ac2961c70077a18763dde3fbc9d04e29c5139b0130c0b2dff93e",
          "sha1": "1fb8794507db86a65bca031a23146b17a46e404e",
          "md5": "53954201d2fcfa39084db14e0dc012f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.2-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.2-SNAPSHOT-plain.jar",
          "size": 12523,
          "sha512": "203d9ceafa2f8087286904cf0b19cdee52886d6f285825ed3f2737a90fbff8839ff02cce3f80b66a0ee0f008b4a0f04c8453826f52ece9daef04d5f8495834e9",
          "sha256": "c51738b93639ac2961c70077a18763dde3fbc9d04e29c5139b0130c0b2dff93e",
          "sha1": "1fb8794507db86a65bca031a23146b17a46e404e",
          "md5": "53954201d2fcfa39084db14e0dc012f2"
        }
      ]
    }
  ]
}
