{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.11-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.11-SNAPSHOT-plain.jar",
          "size": 29392,
          "sha512": "395e4dc376bf8ef44ee6ccbc050a309528af56a36b9690ab2090cfd22dc1e6c88a6c35946365b70bc445d15151951dfd0934933566c9d0a0db775c2ea4f174e6",
          "sha256": "0e6f16e960f3023eb043e890946bf1f6d352418806fb3e4aaba7bfc3deda161d",
          "sha1": "14de69bc0cb7045d85aa9f0149cca0683d10495d",
          "md5": "eda1d016c9f34b9f1b13a4e7f6a68d5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.11-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.11-SNAPSHOT-plain.jar",
          "size": 29392,
          "sha512": "395e4dc376bf8ef44ee6ccbc050a309528af56a36b9690ab2090cfd22dc1e6c88a6c35946365b70bc445d15151951dfd0934933566c9d0a0db775c2ea4f174e6",
          "sha256": "0e6f16e960f3023eb043e890946bf1f6d352418806fb3e4aaba7bfc3deda161d",
          "sha1": "14de69bc0cb7045d85aa9f0149cca0683d10495d",
          "md5": "eda1d016c9f34b9f1b13a4e7f6a68d5a"
        }
      ]
    }
  ]
}
