{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.12-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.12-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.12-SNAPSHOT-plain.jar",
          "size": 29574,
          "sha512": "756ec252d0ea308d70f239221783349fb076cd33d119cd9037910d9686e99be4ade46bd251032b9631b1234102abc4a2b1b11124b56a7801ca4da4ec859afc05",
          "sha256": "208a3209c8c5f6861a83012f06f7007cdac0fe4562a17094c0c1cb1d64b09883",
          "sha1": "9624d40518d369dae8cefcc1a2e485430b84994b",
          "md5": "592aee338ed011948c1cfe30f85b895a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.12-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.12-SNAPSHOT-plain.jar",
          "size": 29574,
          "sha512": "756ec252d0ea308d70f239221783349fb076cd33d119cd9037910d9686e99be4ade46bd251032b9631b1234102abc4a2b1b11124b56a7801ca4da4ec859afc05",
          "sha256": "208a3209c8c5f6861a83012f06f7007cdac0fe4562a17094c0c1cb1d64b09883",
          "sha1": "9624d40518d369dae8cefcc1a2e485430b84994b",
          "md5": "592aee338ed011948c1cfe30f85b895a"
        }
      ]
    }
  ]
}
