{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.8-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.8-SNAPSHOT-plain.jar",
          "size": 29303,
          "sha512": "971ab99613c3c3ca06b84c12f277a2152c8819c4d1ea7677a15c61b7a19f5f8375e37ad7497cd4bc704d6ed08f2bc40103b90ce2ec1be8cead0a1823fbf60160",
          "sha256": "ec814f943bea2a0a2b606b60c4cf4bad47094f93bc81f2774d596ca6b4427678",
          "sha1": "89d346468e201d5853e62094b8a4e0b23ac47fb0",
          "md5": "ec70b3cd29ed7a875fd3ffebfa8eebce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.8-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.8-SNAPSHOT-plain.jar",
          "size": 29303,
          "sha512": "971ab99613c3c3ca06b84c12f277a2152c8819c4d1ea7677a15c61b7a19f5f8375e37ad7497cd4bc704d6ed08f2bc40103b90ce2ec1be8cead0a1823fbf60160",
          "sha256": "ec814f943bea2a0a2b606b60c4cf4bad47094f93bc81f2774d596ca6b4427678",
          "sha1": "89d346468e201d5853e62094b8a4e0b23ac47fb0",
          "md5": "ec70b3cd29ed7a875fd3ffebfa8eebce"
        }
      ]
    }
  ]
}
