{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mrstm",
    "module": "UberEntityService",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberEntityService-0.0.1-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.1-SNAPSHOT-plain.jar",
          "size": 11196,
          "sha512": "0752e5988a6eef93c05001fee36e5b23dbaacbf06211d5eca7d8191c237db3f1db590d96354eb0c6f9e90c3b11734ca5cc45410dea662e04d26c32ec8c5cc08b",
          "sha256": "3445093960177b44c4f4fa4bc451babd647efb34d5293f9bda4273bfbe6a7813",
          "sha1": "491a3adfb4336112eaa971963d5d8fd18c849560",
          "md5": "eedba050a38a0d4f06283003b2cd8b16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "11.7.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberEntityService-0.0.1-SNAPSHOT-plain.jar",
          "url": "UberEntityService-0.0.1-SNAPSHOT-plain.jar",
          "size": 11196,
          "sha512": "0752e5988a6eef93c05001fee36e5b23dbaacbf06211d5eca7d8191c237db3f1db590d96354eb0c6f9e90c3b11734ca5cc45410dea662e04d26c32ec8c5cc08b",
          "sha256": "3445093960177b44c4f4fa4bc451babd647efb34d5293f9bda4273bfbe6a7813",
          "sha1": "491a3adfb4336112eaa971963d5d8fd18c849560",
          "md5": "eedba050a38a0d4f06283003b2cd8b16"
        }
      ]
    }
  ]
}
